

before_install:
	- sudo add-apt-repository ppa:openjdk-r/ppa
	- sudo apt-get -qq update
	- sudo apt-get install -y openjdk-8-jdk
	- sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
language: java
jdk:
	- oraclejdk8
sudo: required
script: sh build-jerytodik.sh

